### ISSUE TITLE
Should the vault allow to remove a strategy? 

### ISSUE THREAD

**Issue by jmonteer** [yearn/yearn-vaults-v3#72]
When revoking a strategy, it is required that it has 0 debt.

Should we add a forcing parameter that allows to take that debt as a loss (reducing price per share)? 

The main problem is that the loss would be irrecoverable and opens the door to strategy rugs. 

My current position is that we shouldn't but sharing here for more info.

**Comment by storming0x** [comment]
> The main problem is that the loss would be irrecoverable and opens the door to strategy rugs.

> My current position is that we shouldn't but sharing here for more info.


Agree, this is the main trade offs and if we put trustless and permissionless above security, we need to think of adding an intentional "backdoor" lever to the vault that does this.

im trying to think of scenarios where this is needed, mainly an emergency exit i would think, but we want to balance that with the fact that the statement,  "we cant rug" should still be upholded in whatever final design we decide on
