### ISSUE TITLE
Should we add a way to restrict deposits to a subset of users? (by whitelist, veYFI tokenholders, ...)

### ISSUE THREAD

**Issue by jmonteer** [yearn/yearn-vaults-v3#74]
I am thinking some vaults could take great advantage of being able to allow deposits only to a subset of users. 

This module, if set, would return a true or false when asked. For example, a module might check if the deposit is coming from a cryptopunk holder. Or from a veYFI tokenholder. Or from a KYC'd account. Or in a simple whitelist. 

Thoughts?

**Comment by storming0x** [comment]
My first thought i would avoid adding it to the design because it seems like something that can be used to censor existing vaults, but if you start the vault as permissionless, you shouldnt be able to switch it to a blocked/whitelisted one

V2 initial versions had this for intention of restricting deposits in testing, but later removed since it was mostly never used in practice.

Adding this feature for unknowing folk, can see it as a way to send a ruling to prohibit or block in the software certain addresses with could be a never ending whack a mole show, i rather we leave for integrators to do this at the UI level and not leave it possible at all in the protocol
